spring.application.name=inventory-management
server.port=8080
spring.data.mongodb.uri=mongodb+srv://swapnildube07_db_user:fE8QIhUfXfyNSSfZ@cluster0.3p2xzqr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=InventoryMangement
spring.data.mongodb.auto-index-creation=true
spring.data.redis.host=redis-19717.crce206.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=19717
spring.data.redis.username=default
spring.data.redis.password=Hm3rDvNTEthFY7LEZZVeQNFDU2rBf9XH
spring.data.redis.timeout=60000
